### ISSUE TITLE
Will this work with angular 16?

### ISSUE THREAD

**Issue by raysuelzer** [raysuelzer/ngx-angular-query-builder#14]
Angular 16 is ivy only. I think this is Ivy, but need to check on that.

**Comment by mperezd** [comment]
Hi, checked with angular 16 and it works.

**Comment by RouR** [comment]
@mperezd How you fix it? 
Please check versions and command `npm i`
I got errors:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: ngx-angular-query-builder@15.0.1
npm ERR! Found: @angular/common@16.0.0
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"16.0.0" from the root project
npm ERR!   peer @angular/common@"16.0.0" from @angular/forms@16.0.0
npm ERR!   node_modules/@angular/forms
npm ERR!     @angular/forms@"16.0.0" from the root project
npm ERR!     peer @angular/forms@">=12.0.0" from @ionic/angular@6.4.1
npm ERR!     node_modules/@ionic/angular
npm ERR!       @ionic/angular@"6.4.1" from the root project
npm ERR!   6 more (@angular/platform-browser, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^15.2.0" from ngx-angular-query-builder@15.0.1
npm ERR! node_modules/ngx-angular-query-builder
npm ERR!   ngx-angular-query-builder@"^15.0.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/common@15.2.9
npm ERR! node_modules/@angular/common
npm ERR!   peer @angular/common@"^15.2.0" from ngx-angular-query-builder@15.0.1
npm ERR!   node_modules/ngx-angular-query-builder
npm ERR!     ngx-angular-query-builder@"^15.0.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

```

**Comment by mperezd** [comment]
@RouR If you need to install it in your project, use --legacy-peer-deps when you install it. It's necessary to change the package.json to make it build without this error. I'll open a pull request with the changes for review.

**Comment by ng-druid** [comment]
This library is a critical component of our socially responsible web editor Quell. Therefore, have taken it upon ourself to upgrade the package to Angular 16. Needs to be some more testing but otherwise it all seems to compile fine. https://github.com/rollthecloudinc/ngx-angular-query-builder/pkgs/npm/ngx-angular-query-builder/96712808

**Comment by raysuelzer** [comment]
Hey all, sorry about this. When I forked this, my goal was similar to @ng-druid , in that since the old project was abandoned I needed to upgrade it. I would be happy to give others the ability to maintain this application since I pretty much only touch it when we are upgrading our angular on our project.

**Comment by ng-druid** [comment]
I honestly think there are better solutions outside of Angular that can be used with module federation. However, that is much larger of a task than simply upgrading this lib. Upgrading the lib between versions is fairly straight forward. However, if you come across this lib probably wouldn't recommend it. There are more powerful react solutions that can be used with module federation.

**Comment by raysuelzer** [comment]
I'm really sorry I haven't gotten around to updating this. I just need to make sure that it's not going to break things and I haven't had the time to sit down and really do that.

**Comment by raysuelzer** [comment]
Okay, there should be a v16.0.0 on npm now for angular 16. I'm not running angular 16 and didn't have time to test fully, but try that if you need angular 16.
