### ISSUE TITLE
Angular 17 upgrade, along with Prettier and test cases fix

### ISSUE THREAD

**Issue by shivambindal93** [raysuelzer/ngx-angular-query-builder#21]
Hello @raysuelzer ,

I have created a pull request https://github.com/raysuelzer/ngx-angular-query-builder/pull/20 for the angular 17 upgrade. This PR also bears changes for Prettier and Test cases fix Please check it if you can.

Thanks.

**Comment by raysuelzer** [comment]
Merged!
