### ISSUE TITLE
QueryList doesn't get updated for the queryInput custom templates when ivy is enabled

### ISSUE THREAD

**Issue by ravijoshi007** [raysuelzer/ngx-angular-query-builder#3]

**Comment by ravijoshi007** [comment]
I've fixed this issue but I'm unable to raise a PR for that. It seems like I don't have the permission to check-in the code. @raysuelzer could you please help me with that ?

**Comment by ravijoshi007** [comment]
@raysuelzer could you please share the update on this ?

**Comment by raysuelzer** [comment]
Sorry, I merged the PR and published version 0.0.3 with your change.

**Comment by ravijoshi007** [comment]
@raysuelzer thanks a lot.
